# Generated by Django 3.1.7 on 2021-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='new_prizes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
